### PR TITLE
Update download location

### PR DESCRIPTION
**Pull request by mattridgway**
Updated the download location so it uses VS 2015 professional update 2. 
Not sure if you will also want to go through and update the locations for the other editions (enterprise/community), however I need this for work I am doing and wanted to share.

### CODE REVIEW

**Comment by mattridgway** [comment]
In doing some testing I've discovered the link I've updated is only the update. Not the entire install, let me correct it before you accept

**Comment by KennethB** [comment]
http://download.microsoft.com/download/5/8/9/589A8843-BA4D-4E63-BCB2-B2380E5556FD/vs_professional.exe
In my testing this link pulls the VS Professional installer which pulls the latest update from the server.
Are you seeing something different?

**Comment by mattridgway** [comment]
Sorry for the delay, been busy at work. I was finding the installer wasn't updating to include update 2. I believe I've found the correct download link (http://download.microsoft.com/download/D/2/8/D28D3B41-BF4A-409A-AFB5-2C82C216D4E1/vs_professional_ENU.exe) I will do some proper testing first, on a clean windows install and then update the PR. But first check looks ok.

**Comment by Workshop2** [comment]
I just found this link and was going to send a pull request too. @KennethB can this be merged soon?
http://download.microsoft.com/download/D/2/8/D28D3B41-BF4A-409A-AFB5-2C82C216D4E1/vs_professional_ENU.exe

**Comment by KennethB** [comment]
Not going to merge the above links.  They initiate a download that pulls the executable from the original link which so far has always pulled the latest released bits for visual studio.

**Pull request closed without merging**
